server:
  port: 9112
spring:
  application:
    name: jeecg-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 服务端点检查
management:
  endpoints:
    web:
      exposure:
        include: '*'